(ns cesiumdemo.sampledata)

(def sample "UIC	CMP	ALD	CRD	LAD	RDD	ORIG_GEO	ORIG_NAME	POE_GEO	POE_NAME	POD_GEO	POD_NAME	SRC	PAX	TOTAL_STONS
uic_18	A	N040	N011	N037	N028	HCTL	FT BRAGG	TMKH	POPE AAF	FLPR	EUROPE	SRC_6	100	0
uic_18	A	N022	N011	N019	N010	HCTL	FT BRAGG	TMKH	POPE AAF	FLPR	EUROPE	SRC_6	650	32.6
uic_18	A	N025	N011	N002	C023	HCTL	FT BRAGG	ZBES	WILMINGTON	CHCY	EUROPE	SRC_6	0	955.4")

(def sample-moves [{:RDD -28, :SRC "SRC_6", :ORIG_NAME "FT BRAGG", :TOTAL_STONS 0, :UIC "uic_18", :POE_GEO "TMKH", :POE_NAME "POPE AAF", :ALD -40, :POD_GEO "FLPR", :LAD -37, :CRD -11, :PAX 100, :POD_NAME "EUROPE", :ORIG_GEO "HCTL", :CMP "A"} {:RDD -10, :SRC "SRC_6", :ORIG_NAME "FT BRAGG", :TOTAL_STONS 32.6, :UIC "uic_18", :POE_GEO "TMKH", :POE_NAME "POPE AAF", :ALD -22, :POD_GEO "FLPR", :LAD -19, :CRD -11, :PAX 650, :POD_NAME "EUROPE", :ORIG_GEO "HCTL", :CMP "A"} {:RDD 23, :SRC "SRC_6", :ORIG_NAME "FT BRAGG", :TOTAL_STONS 955.4, :UIC "uic_18", :POE_GEO "ZBES", :POE_NAME "WILMINGTON", :ALD -25, :POD_GEO "CHCY", :LAD -2, :CRD -11, :PAX 0, :POD_NAME "EUROPE", :ORIG_GEO "HCTL", :CMP "A"}])
